target_sources(receiver PRIVATE rtsp.cpp rtsp_listener.cpp)
add_library(receiver-rtsp-message STATIC rtsp_message.cpp)
target_include_directories(receiver-rtsp-message PUBLIC "${CMAKE_SOURCE_DIR}/src")
target_compile_options(receiver-rtsp-message PRIVATE -Wall -Wextra -Wshadow -Wformat=2 -fno-common)
target_link_libraries(receiver PUBLIC receiver-rtsp-message)
add_library(receiver-rtsp-parameters STATIC rtsp_parameters.cpp)
target_sources(receiver-rtsp-parameters PUBLIC FILE_SET CXX_MODULES FILES rtsp_parameters.cppm)
target_include_directories(receiver-rtsp-parameters PUBLIC "${CMAKE_SOURCE_DIR}/src")
target_compile_options(receiver-rtsp-parameters PRIVATE -Wall -Wextra -Wshadow -Wformat=2 -fno-common)
set_target_properties(receiver-rtsp-parameters PROPERTIES CXX_SCAN_FOR_MODULES ON)
set_source_files_properties(rtsp.cpp TARGET_DIRECTORY receiver PROPERTIES CXX_SCAN_FOR_MODULES ON)
target_link_libraries(receiver-rtsp-parameters PUBLIC receiver-rtsp-message)
target_link_libraries(receiver PUBLIC receiver-rtsp-parameters)
add_library(receiver-rtsp-request STATIC rtsp_request_reader.cpp)
target_sources(receiver-rtsp-request PUBLIC FILE_SET CXX_MODULES FILES rtsp_request_reader.cppm)
target_include_directories(receiver-rtsp-request PUBLIC "${CMAKE_SOURCE_DIR}/src")
target_compile_options(receiver-rtsp-request PRIVATE -Wall -Wextra -Wshadow -Wformat=2 -fno-common)
set_target_properties(receiver-rtsp-request PROPERTIES CXX_SCAN_FOR_MODULES ON)
target_link_libraries(receiver-rtsp-request PUBLIC receiver-rtsp-message)
target_link_libraries(receiver PUBLIC receiver-rtsp-request)
